apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
    categories: "Developer Tools"
    description: An operator to install TektonCD Pipeline
    containerImage: quay.io/openshift-pipeline/nikthoma_tektoncd-pipeline-operator:v0.2.0-1
    createdAt: 2019-03-15T19:44:21Z
    certified: "false"
    support: Red Hat, Inc.
    repository: https://github.com/openshift/tektoncd-pipeline-operator
    alm-examples: |
      [
        {
          "apiVersion": "tekton.dev/v1alpha1",
          "kind": "Install",
          "metadata": {
            "name": "example-install",
            "namespace": "tekton-pipelines"
        },
          "spec": {}
        }
      ]
  name: tektoncd-pipeline-operator.v0.0.1
  namespace: tekton-pipelines
spec:
  version: 0.0.1
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  maintainers:
  - name: Red Hat, Inc.
    email: customerservice@redhat.com
  icon:
  - base64data: /9j/4AAQSkZJRgABAQIAdgB2AAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAAoACgDAREAAhEBAxEB/8QAGQAAAwEBAQAAAAAAAAAAAAAABQYHCAIE/8QAKxAAAQQBAwMEAgEFAAAAAAAAAQIDBAUGBxESABMhFBUiQTEyYSNRUnGR/8QAGgEAAwEBAQEAAAAAAAAAAAAAAwQFBgcBAv/EAC8RAAEDAwMDAgUDBQAAAAAAAAECAxEABCEFEjFBUWETIiMycYGhFJGxQtHh8PH/2gAMAwEAAhEDEQA/ANpZbStz7zN8tmX1pCtMbso/YRGmrZLkRTDfBpAHjkpRVxOx3X4O4J6o/qNjSGwBBH5mr9mk/CaCQQsHkcEE5PgdfFFno1/Bxxqdq3q3IpyppRi17ElmE6pPniH3U7Kcc22CuHFIP/epzriE54py3Ql5/wBPTLb1M5UQVDzA4A7TJryYkmbd483J0w1ocevvTFTldYzUT2Vr2+0q3cbP8gkD7H10jvLo+Av3duaq3iG7G526xYfBn5kpKD+49p+n5pNeppqqxvUKxyK+cyiPk9fTR4UueVLYfElAeStCNkfNJWQlI4hvY+SSehtME/EUTunvVZ/Um0rOmstIDBbWslKcEFJ2wTJwYkkzumtUdUq5TUrznHIL+r+HzGw6HJqJLsxlKtm5XpEc2OQ+1JW5uD14VxCa0enOqGl3E/07QD1G8wr9wKyXqJ79k+QWkzKa/IG8qcdW6mM9GPZDQc2DTY23CUo2Vy34+CNvs566cW6opg7q7loLdrpts2bdTZt4AkHMxyfqcRz/ABSlWxrOiksS48bI2Mm7pcq0V8YkpKAClZ8brClniQk+NiTv+OiWlqUnceaJq2qN3SVNygsxCtx79PEDOefzWuMfpXbzXDGLjK4UiJPlYm1fya0nZpu1bUlgurR/mlDpSP7bfx1dCMbq4hc3YZ0523tzKQspCuuw+6J7SKvvXtZWlPUTA2c4rY3YlCHa1b3qq6WU8g27tsUqAIJQoeFDff7HkDoL7XqpgGCOKtaJq50l5RUnc2sQpPcdwehHIqB5LnjlpClxZeF2rthAdfo7BLzT9tTvMFYDy0lB74SFtpIKR4I4k9BQCvkZ47itk3aC2UFNvJ2KhxMbW3AYO0HG2YJmfrS5Q6g12A0/fdw23eaqE+kqvYoMioiSXJBR3XHnZCg7vyQ2DxBSAN/9Ps28wBikdRSu9cJLglWVbyFkbZgAJx1PmnSlyGHpTkt1Pk1asu1EsW44s41fKCIVLFU6hDUcyHyT+7qCo/JaiQogDbptLBeSMwn+azd04bptKEna2OJ5J7wP+Cqfges8PK8ifw2+x+VQXjSngwlbgfhz+0QHvTSUgJdLZOy07BSfPjwdvl6zU236qTKfyJ4kdJ6VIWkJ4M0f1JzePp/ij9+4htx5TrUSI26opQt91QSgLUP1SCd1H6APSZpvTrM31wGpgZJ+gyY89vNRrHNWK3EdIH6dqzcF5GsJVf7o3BdMBUt2coFaZBSWv1cCxur8dEaZJgVa1C2Nzf8ArEewhJiRMBIwRz0jiuM81dobjRzN8csbN+wsRIsaNqwYguOxklb5RFU5IQntI8La8lQ/Hnp23tV+skxjB8+cVKDRafQ4kQMGPtmgmgul+MajybdWVlu6qMUmrrfRrmGXHsbRTaFyrJSyAVpdBaKEElI2J2322avHl2oTswVCZ4IHQfbrQH3yo4/0dBVKx7Q69pMgoIhyqGrDsRtJNtSQUQ1ic0p5DqBHW+VkFlHec2ASFEcQT48hXqDa21nb71gAmcYjMRyYpFQUpUk0Q1nq8tuZ+PRqupu5lNEfVPleyuRUyvVtLQqOCZCgA2PmTx8kgA+D1OQAeTVfTnmmUOFRG4iBMxBmeOvFRm3z2shY7ndbcIVTWNpPM6PiyqST3Y8uM42Wv6jSVtOGQGUFXE8QV7gnz1RZtlKUkpyO8jr/AGorp9yFAzAjdPIP5xOKHPao0trhcOPGhOC2eyNzIJOFvUEtx6a+qUe1AUeCWkcE9tXIkp5oG/xB3fbslpcJPyxG6RAxz3/xUt5zarviKrWjFTn1XqNk06ZjeS1eN3zXuUhF85AU4iz5IbSI/pVKIa7KQOKv17adj5PSd+phVugJUkrTj27vl8z1nt3pVJUVZGKt/UeiV//Z
    mediatype: image/png
  links:
  - name: Tekton Pipeline GitHub Repository
    url: https://github.com/tektoncd/pipeline
  - name: Tekton Pipeline Operator GitHub Repository
    url: https://github.com/openshift/tektoncd-pipeline-operator
  keywords: ['tektoncd', 'build', 'pipeline']
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - name: installs.tekton.dev
      version: v1alpha1
      kind: Install
      displayName: TektonCD-Pipeline Install
      description: CRD to trigger install/delete of TektonCD-Pipeline
      resources:
      - kind: Pod
        version: v1
      - kind: Service
        version: v1
      - kind: ServiceAccount
        version: v1
      - kind: ConfigMap
        version: v1
      specDescriptors: []
      statusDescriptors:
      - description: List of resources installed by the operator for this cr
        displayName: Installed Resources
        path: resources
      - description: Version of Tektoncd Pipeline installed
        displayName: Tektoncd Pipeline Version
        path: version
  description: Kubernetes operator to install TektonCD-Pipeline
  displayName: TektonCD Pipeline Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - tekton.dev
          resources:
          - '*'
          - installs
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          verbs:
          - get
          - create
          - update
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          verbs:
          - get
          - create
          - update
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - create
          - update
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - build.knative.dev
          resources:
          - builds
          - buildtemplates
          - clusterbuildtemplates
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments/finalizers
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        serviceAccountName: tektoncd-pipeline-operator
      deployments:
      - name: tektoncd-pipeline-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: tektoncd-pipeline-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: tektoncd-pipeline-operator
            spec:
              containers:
              - command:
                - tektoncd-pipeline-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: tektoncd-pipeline-operator
                image: quay.io/openshift-pipeline/nikthoma_tektoncd-pipeline-operator:v0.2.0-1
                imagePullPolicy: Always
                name: tektoncd-pipeline-operator
                resources: {}
              serviceAccountName: tektoncd-pipeline-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
